use opsec_dashboard::checks::{Status, parse_dns, parse_dnscrypt, resolv_nameservers};

#[test]
fn active_service_passes() {
    assert!(matches!(parse_dnscrypt("active\n").status, Status::Pass(_)));
}

#[test]
fn inactive_service_fails() {
    let msg = match parse_dnscrypt("inactive\n").status {
        Status::Fail(m) => m,
        other => panic!("expected Fail, got {other:?}"),
    };
    assert!(msg.contains("inactive"));
}

#[test]
fn failed_service_fails() {
    assert!(matches!(parse_dnscrypt("failed\n").status, Status::Fail(_)));
}

#[test]
fn activating_service_fails() {
    assert!(matches!(
        parse_dnscrypt("activating\n").status,
        Status::Fail(_)
    ));
}

#[test]
fn empty_state_is_unknown() {
    assert!(matches!(parse_dnscrypt("").status, Status::Unknown(_)));
    assert!(matches!(
        parse_dnscrypt("   \n  ").status,
        Status::Unknown(_)
    ));
}

// A running dnscrypt-proxy proves nothing if resolv.conf points elsewhere:
// every query bypasses it and leaks to the upstream resolver in the clear.
#[test]
fn active_but_bypassed_by_resolv_conf_warns() {
    let resolv = "# Generated by NetworkManager\nnameserver 1.1.1.1\n";
    let msg = match parse_dns("active", Some(resolv)).status {
        Status::Warn(m) => m,
        other => panic!("a bypassed resolver must not pass, got {other:?}"),
    };
    assert!(msg.contains("1.1.1.1"), "got {msg}");
}

#[test]
fn active_with_loopback_resolver_passes() {
    let msg = match parse_dns("active", Some("nameserver 127.0.0.1\n")).status {
        Status::Pass(m) => m,
        other => panic!("expected Pass, got {other:?}"),
    };
    assert!(msg.contains("127.0.0.1"));
}

#[test]
fn active_with_ipv6_loopback_resolver_passes() {
    assert!(matches!(
        parse_dns("active", Some("nameserver ::1\n")).status,
        Status::Pass(_)
    ));
}

#[test]
fn any_non_loopback_resolver_is_reported() {
    let resolv = "nameserver 127.0.0.1\nnameserver 8.8.8.8\n";
    let msg = match parse_dns("active", Some(resolv)).status {
        Status::Warn(m) => m,
        other => panic!("a fallback resolver still leaks, got {other:?}"),
    };
    assert!(msg.contains("8.8.8.8"), "got {msg}");
}

#[test]
fn active_with_no_nameserver_warns() {
    assert!(matches!(
        parse_dns("active", Some("# nothing here\n")).status,
        Status::Warn(_)
    ));
}

#[test]
fn nameserver_extraction_ignores_comments() {
    let resolv = "# nameserver 9.9.9.9\nnameserver 127.0.0.1 # local\noptions edns0\n";
    assert_eq!(resolv_nameservers(resolv), vec!["127.0.0.1"]);
}
